Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
  
    # Use a private network so that we don't have to worry about forwarding ports
    config.vm.network "private_network", ip: "192.168.50.15"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  
    # use docker provionning
    config.vm.provision "docker" do |d|
        d.run "couchdb-dev", image: "couchdb", args: "-p 5984:5984"
    end
  
end