
Vagrant.configure("2") do |config|
  # Specify your hostname if you like

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "bento/ubuntu-16.04"
    master.vm.network "private_network", ip: "192.168.50.15"
    master.vm.synced_folder ".", "/vagrant"
  
    master.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-master"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    master.vm.provision "docker"
    master.vm.provision "shell", path: "install-k8s.sh"
    master.vm.provision "shell", path: "init-master.sh"
  end
end
