Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
  
    # Use a private network so that we don't have to worry about forwarding ports
    config.vm.network "forwarded_port", guest: 5984, host: 5984

    config.vm.synced_folder ".", "/vagrant", disabled: false
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  
    # use docker provionning
    config.vm.provision "docker" do |d|
        d.build_image "/vagrant", args: "-t couchdb-admin"
        d.run "couchdb-dev", image: "couchdb:2.3", args: "-p 5984:5984"
    end
    config.vm.provision "shell", path: "init.sh"
end
